// This file is auto-generated by @hey-api/openapi-ts

export const UserSchema = {
	type: 'object',
	properties: {
		id: {
			type: 'number',
			description: 'Уникальный идентификатор пользователя'
		},
		login: {
			type: 'string',
			description: 'Email адрес пользователя'
		},
		full_name: {
			type: 'string',
			example: 'Иван Иванов',
			description: 'Полное имя пользователя'
		},
		role: {
			$ref: '#/components/schemas/UserRole'
		}
	},
	required: [ 'id', 'login', 'full_name', 'role' ],
	description: 'Модель пользователя системы'
} as const

export const UserRoleSchema = {
	type: 'string',
	enum: [ 'ADMIN', 'EDITOR', 'VIEWER' ],
	example: 'VIEWER'
} as const

export const UserRequestBodySchema = {
	type: 'object',
	properties: {
		login: {
			type: 'string',
			description: 'Email адрес пользователя'
		},
		full_name: {
			type: 'string',
			example: 'Иван Иванов',
			description: 'Полное имя пользователя'
		},
		password: {
			type: 'string'
		},
		role: {
			$ref: '#/components/schemas/UserRole'
		}
	},
	required: [ 'login', 'password', 'full_name', 'role' ]
} as const

export const PaginationMetaSchema = {
	type: 'object',
	properties: {
		currentPage: {
			type: 'integer'
		},
		from: {
			type: 'integer'
		},
		lastPage: {
			type: 'integer'
		},
		perPage: {
			type: 'integer'
		},
		to: {
			type: 'integer'
		},
		total: {
			type: 'integer'
		}
	},
	required: [ 'from', 'lastPage', 'perPage', 'to', 'total', 'currentPage' ]
} as const

export const TableSchema = {
	type: 'object',
	properties: {
		id: {
			type: 'integer',
			description: 'Уникальный идентификатор таблицы'
		},
		full_name: {
			type: 'string',
			example: 'Таблицы 1',
			description: 'Имя таблицы'
		}
	}
} as const

export const TableResponseBodySchema = {
	type: 'object',
	properties: {
		data: {
			$ref: '#/components/schemas/Table'
		}
	},
	required: ['data']
} as const

export const TableListResponseBodySchema = {
	type: 'object',
	properties: {
		data: {
			type: 'array',
			items: {
				$ref: '#/components/schemas/Table'
			}
		}
	},
	required: ['data']
} as const

export const TableRequestBodySchema = {
	type: 'object',
	properties: {
		data: {
			type: 'object',
			properties: {
				id: {
					type: 'number'
				},
				title: {
					type: 'string'
				}
			},
			required: ['id']
		}
	},
	required: ['data']
} as const