// This file is auto-generated by @hey-api/openapi-ts

export const UserSchema = {
	type: 'object',
	properties: {
		id: {
			type: 'number',
			description: 'Уникальный идентификатор пользователя',
			example: 1
		},
		login: {
			type: 'string',
			description: 'Email адрес пользователя',
			example: 'ivanov@example.com'
		},
		first_name: {
			type: 'string',
			example: 'Иван'
		},
		last_name: {
			type: 'string',
			example: 'Иванов'
		},
		middle_name: {
			type: 'string',
			example: 'Иванович'
		},
		role: {
			$ref: '#/components/schemas/UserRole'
		}
	},
	required: [ 'id', 'login', 'first_name', 'last_name', 'middle_name', 'role' ],
	description: 'Модель пользователя системы'
} as const

export const UserRoleSchema = {
	type: 'string',
	enum: [ 'ADMIN', 'EDITOR', 'VIEWER' ],
	example: 'ADMIN'
} as const

export const UserRequestBodySchema = {
	type: 'object',
	properties: {
		login: {
			type: 'string',
			description: 'Email адрес пользователя',
			example: 'petrov@example.com'
		},
		first_name: {
			type: 'string',
			example: 'Петр'
		},
		last_name: {
			type: 'string',
			example: 'Петров'
		},
		middle_name: {
			type: 'string',
			example: 'Петрович'
		},
		password: {
			type: 'string',
			example: 'securePassword123'
		},
		role: {
			$ref: '#/components/schemas/UserRole'
		}
	},
	required: [ 'login', 'password', 'first_name', 'last_name', 'middle_name', 'role' ]
} as const

export const PaginationMetaSchema = {
	type: 'object',
	properties: {
		currentPage: {
			type: 'integer'
		},
		from: {
			type: 'integer'
		},
		lastPage: {
			type: 'integer'
		},
		perPage: {
			type: 'integer'
		},
		to: {
			type: 'integer'
		},
		total: {
			type: 'integer'
		}
	},
	required: [ 'from', 'lastPage', 'perPage', 'to', 'total', 'currentPage' ]
} as const