// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios'

import type { UserLoginData, UserLoginError, UserLoginResponse, UserLogoutError, UserLogoutResponse, GetUsersData, GetUsersError, GetUsersResponse, AddUserData, AddUserError, AddUserResponse, DeleteUserData, DeleteUserError, DeleteUserResponse } from './types.gen'

export const client = createClient(createConfig())

export class AuthService {
	public static userLogin<ThrowOnError extends boolean = false>(options: Options<UserLoginData, ThrowOnError>) {
		return (options?.client ?? client).post<UserLoginResponse, UserLoginError, ThrowOnError>({
			...options,
			url: '/auth/login'
		})
	}

	public static userLogout<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
		return (options?.client ?? client).post<UserLogoutResponse, UserLogoutError, ThrowOnError>({
			...options,
			url: '/auth/logout'
		})
	}

}

export class UsersService {
	public static getUsers<ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) {
		return (options?.client ?? client).get<GetUsersResponse, GetUsersError, ThrowOnError>({
			...options,
			url: '/users'
		})
	}

	public static addUser<ThrowOnError extends boolean = false>(options: Options<AddUserData, ThrowOnError>) {
		return (options?.client ?? client).post<AddUserResponse, AddUserError, ThrowOnError>({
			...options,
			url: '/users'
		})
	}

	public static deleteUser<ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) {
		return (options?.client ?? client).delete<DeleteUserResponse, DeleteUserError, ThrowOnError>({
			...options,
			url: '/users/{id}'
		})
	}

}