// This file is auto-generated by @hey-api/openapi-ts

/**
 * Модель пользователя системы
 */
export type User = {

	/**
	 * Уникальный идентификатор пользователя
	 */
	id: number;

	/**
	 * Email адрес пользователя
	 */
	login: string;
<<<<<<< HEAD
	first_name: string;
	last_name: string;
	middle_name: string;
=======

	/**
	 * Полное имя пользователя
	 */
	full_name: string;
>>>>>>> master
	role: UserRole;
};

export type UserRole = 'ADMIN' | 'EDITOR' | 'VIEWER';

export const UserRole = {
	ADMIN: 'ADMIN',
	EDITOR: 'EDITOR',
	VIEWER: 'VIEWER'
} as const

export type UserRequestBody = {

	/**
	 * Email адрес пользователя
	 */
	login: string;
<<<<<<< HEAD
	first_name: string;
	last_name: string;
	middle_name: string;
=======

	/**
	 * Полное имя пользователя
	 */
	full_name: string;
>>>>>>> master
	password: string;
	role: UserRole;
};

export type PaginationMeta = {
	currentPage: number;
	from: number;
	lastPage: number;
	perPage: number;
	to: number;
	total: number;
};
<<<<<<< HEAD
=======

export type Table = {

	/**
	 * Уникальный идентификатор таблицы
	 */
	id?: number;

	/**
	 * Имя таблицы
	 */
	full_name?: string;
};

export type TableResponseBody = {
	data: Table;
};

export type TableListResponseBody = {
	data: Array<Table>;
};

export type TableRequestBody = {
	data: {
		id: number;
		title?: string;
	};
};
>>>>>>> master

export type UserLoginData = {
	body: {
		login: string;
		password: string;
	};
};

export type UserLoginResponse = ({
	user: User;
	token: string;
});

export type UserLoginError = (unknown);

export type UserLogoutResponse = (void);

export type UserLogoutError = (unknown);

export type GetUsersData = {
	query?: {
		login?: string;
		page?: number;
		pageSize?: number;
	};
};

<<<<<<< HEAD
export type GetUsersResponse = ({
	users?: Array<User>;
	meta?: PaginationMeta;
});

export type GetUsersError = (unknown);

export type AddUserData = {
	body: UserRequestBody;
};

export type AddUserResponse = (User);

export type AddUserError = (unknown);

export type DeleteUserData = {
	path: {
		user_id: number;
	};
};

export type DeleteUserResponse = ({
	id?: number;
});

export type DeleteUserError = (unknown);
=======
export type GetUsersResponse = (unknown);

export type GetUsersError = (unknown);

export type AddUserData = {
	body: UserRequestBody;
};

export type AddUserResponse = (User);

export type AddUserError = (unknown);

export type DeleteUserData = {
	path: {
		user_id: number;
	};
};

export type DeleteUserResponse = ({
	id?: number;
});

export type DeleteUserError = (unknown);

export type GetAllTablesResponse = (TableListResponseBody);

export type GetAllTablesError = (unknown);

export type CreateTableData = {
	body: TableRequestBody;
};

export type CreateTableResponse = (TableListResponseBody);

export type CreateTableError = (unknown);

export type GetTabletByIdData = {
	path: {
		id: number;
	};
};

export type GetTabletByIdResponse = (TableResponseBody);

export type GetTabletByIdError = (unknown);

export type UpdateTableData = {
	body: TableRequestBody;
	path: {
		id: number;
	};
};

export type UpdateTableResponse = (TableListResponseBody);

export type UpdateTableError = (unknown);

export type DeleteTablesData = {
	path: {
		id: number;
	};
};

export type DeleteTablesResponse = (unknown);

export type DeleteTablesError = (unknown);
>>>>>>> master
