// This file is auto-generated by @hey-api/openapi-ts

/**
 * Модель пользователя системы
 */
export type User = {

	/**
	 * Уникальный идентификатор пользователя
	 */
	id: number;

	/**
	 * Email адрес пользователя
	 */
	login: string;

	/**
	 * Полное имя пользователя
	 */
	full_name: string;
	role: UserRole;
};

export type UserRole = 'ADMIN' | 'EDITOR' | 'VIEWER';

export const UserRole = {
	ADMIN: 'ADMIN',
	EDITOR: 'EDITOR',
	VIEWER: 'VIEWER'
} as const

export type UserRequestBody = {

	/**
	 * Email адрес пользователя
	 */
	login: string;

	/**
	 * Полное имя пользователя
	 */
	full_name: string;
	password: string;
	role: UserRole;
};

export type PaginationMeta = {
	currentPage: number;
	from: number;
	lastPage: number;
	perPage: number;
	to: number;
	total: number;
};

export type Table = {

	/**
	 * Уникальный идентификатор таблицы
	 */
	id?: number;

	/**
	 * Имя таблицы
	 */
	title?: string;
};

export type TableResponseBody = {
	data: Table;
};

export type TableListResponseBody = {
	data: Array<Table>;
};

export type TableRequestBody = {
	data: {
		title?: string;
	};
};

export type Columns = {

	/**
	 * Уникальный идентификатор колонки
	 */
	id: number;

	/**
	 * Внешний ключ таблицы
	 */
	table_id: number;

	/**
	 * Название колонки
	 */
	title: string;
	type: 'string' | 'number' | 'timestamp' | 'list';
};

export type type = 'string' | 'number' | 'timestamp' | 'list';

export const type = {
	STRING: 'string',
	NUMBER: 'number',
	TIMESTAMP: 'timestamp',
	LIST: 'list'
} as const

export type ColumnResponseBody = {
	data: Columns;
};

export type ColumnListResponseBody = {
	data: Array<Columns>;
};

export type ColumnRequestBody = {
	data: {

		/**
		 * Внешний ключ таблицы
		 */
		table_id: number;

		/**
		 * Название колонки
		 */
		title: string;
		type: 'string' | 'number' | 'timestamp' | 'list';
	};
};

export type UserLoginData = {
	body: {
		login: string;
		password: string;
	};
};

export type UserLoginResponse = ({
	user: User;
	token: string;
});

export type UserLoginError = (unknown);

export type UserLogoutResponse = (void);

export type UserLogoutError = (unknown);

export type GetUsersData = {
	query?: {
		login?: string;
		page?: number;
		pageSize?: number;
	};
};

export type GetUsersResponse = (unknown);

export type GetUsersError = (unknown);

export type AddUserData = {
	body: UserRequestBody;
};

export type AddUserResponse = (User);

export type AddUserError = (unknown);

export type DeleteUserData = {
	path: {
		user_id: number;
	};
};

export type DeleteUserResponse = ({
	id?: number;
});

export type DeleteUserError = (unknown);

export type GetAllTablesData = {
	query?: {
		page?: number;
		pageSize?: number;
	};
};

export type GetAllTablesResponse = (TableListResponseBody);

export type GetAllTablesError = (unknown);

export type CreateTableData = {
	body: TableRequestBody;
};

export type CreateTableResponse = (TableListResponseBody);

export type CreateTableError = (unknown);

export type GetTabletByIdData = {
	path: {
		id: number;
	};
};

export type GetTabletByIdResponse = (TableResponseBody);

export type GetTabletByIdError = (unknown);

export type UpdateTableData = {
	body: TableRequestBody;
	path: {
		id: number;
	};
};

export type UpdateTableResponse = (TableListResponseBody);

export type UpdateTableError = (unknown);

export type DeleteTablesData = {
	path: {
		id: number;
	};
};

export type DeleteTablesResponse = (unknown);

export type DeleteTablesError = (unknown);

export type CreateColumnData = {
	body: ColumnRequestBody;
};

export type CreateColumnResponse = (ColumnListResponseBody);

export type CreateColumnError = (unknown);

export type UpdateColumnsData = {
	body: ColumnRequestBody;
	path: {
		id: number;
	};
};

export type UpdateColumnsResponse = (ColumnListResponseBody);

export type UpdateColumnsError = (unknown);

export type DeleteColumnsData = {
	path: {
		id: number;
	};
};

export type DeleteColumnsResponse = (unknown);

export type DeleteColumnsError = (unknown);