openapi: 3.0.3
info:
  title: Constructor Form
  version: 0.0.1
servers:
  - url: http://localhost:4010
    description: Мок сервер
tags:
  - name: auth
    description: Все связанное с авторизацией
  - name: users
    description: Все связанное с пользователями
paths:
  /auth/login:
    $ref: './auth/paths.yaml#/Login'
  /auth/logout:
    $ref: './auth/paths.yaml#/Logout'

  /users:
    $ref: './users/paths.yaml#/UsersPath'
  /users/{id}:
    $ref: './users/paths.yaml#/UsersIdPath'

  # Tables
  /tables:
    $ref: './tables/paths.yaml#/TablesPath'
  /tables/{id}:
    $ref: './tables/paths.yaml#/TableIdPath'
  
  # Columns
  /columns:
    $ref: './columns/paths.yaml#/ColumnPath'
  /columns/{id}:
    $ref: './columns/paths.yaml#/ColumnIdPath'

  # Rows
  /rows:
    $ref: './rows/paths.yaml#/RowsPath'
  /rows/{id}:
    $ref: './rows/paths.yaml#/RowIdPath'

components:
  schemas:
    User:
      $ref: './users/schemas.yaml#/User'
    UserRole:
      $ref: './users/schemas.yaml#/UserRole'
    UserRequestBody:
      $ref: './users/schemas.yaml#/UserRequestBody'
    PaginationMeta:
      $ref: './common/schemas.yaml#/PaginationMeta'
    
    Table: 
      $ref: './tables/schemas.yaml#/Table'
    TableResponseBody:
      $ref: './tables/schemas.yaml#/TableResponseBody'
    TableListResponseBody:
      $ref: './tables/schemas.yaml#/TableListResponseBody'
    TableRequestBody:
      $ref: './tables/schemas.yaml#/TableRequestBody'
    TableCreateRequestBody:
      $ref: './tables/schemas.yaml#/TableCreateRequestBody'

    Columns:
      $ref: './columns/schemas.yaml#/Columns'
    ColumnResponseBody:
      $ref: './columns/schemas.yaml#/ColumnResponseBody'
    ColumnListResponseBody:
      $ref: './columns/schemas.yaml#/ColumnListResponseBody'
    ColumnRequestBody:
      $ref: './columns/schemas.yaml#/ColumnRequestBody'

    Rows:
      $ref: './rows/schemas.yaml#/Rows'
    RowsResponseBody:
      $ref: './rows/schemas.yaml#/RowsResponseBody'
    RowListResponseBody:
      $ref: './rows/schemas.yaml#/RowListResponseBody'
    RowRequestBody:
      $ref: './rows/schemas.yaml#/RowRequestBody'

    Cells:
      $ref: './cells/schemas.yaml#/Cells'
  
  securitySchemes:
    $ref: './common/security.yaml'
